name: organize
description: "Organize - Digital Planner Application"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.8
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.4.1
  flutter_colorpicker: ^1.1.0
  signature: ^5.4.0

  # PDF & Document Handling
  flutter_pdfview: ^1.4.1+1
  pdf: ^3.11.3
  printing: ^5.14.2


  # Drawing & Apple Pencil Support
  flutter_signature_pad: ^3.0.1
  perfect_freehand: ^2.4.1
  flutter_drawing_board: ^0.9.8



  # Firebase (Database & Authentication) - Stable versions
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.6.0
  firebase_analytics: ^10.7.4

  # Authentication Options
  google_sign_in: ^7.1.1
  sign_in_with_apple: ^7.0.1

  # File & Storage Management
  path_provider: ^2.1.5
  file_picker: ^10.3.2
  shared_preferences: ^2.5.3
  image_picker: ^1.2.0
  url_launcher: ^6.3.1


  # In-App Purchases & Subscriptions
  in_app_purchase: ^3.2.3
  purchases_flutter: ^9.4.0

  # State Management
  provider: ^6.1.5+1
  get: ^4.7.2

  # Drag & Drop for Stickers
  draggable_widget: ^2.0.0
  flutter_draggable_gridview: ^0.0.13

  # Utilities
  uuid: ^4.5.1
  intl: ^0.19.0
  permission_handler: ^12.0.1
  device_info_plus: ^11.5.0
  package_info_plus: ^4.2.0

  # HTTP & Network
  http: ^1.5.0
  dio: ^5.9.0
  syncfusion_flutter_pdf: ^31.1.18
  pdfx: ^2.6.0
  syncfusion_flutter_pdfviewer: ^31.1.18




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Assets for your app
  assets:
    - assets/images/
    - assets/stickers/
    - assets/icons/
    - assets/templates/
