// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCqWRqztOVQeRozkzJOYxDXwbBzWPBzSU',
    appId: '1:667210571249:web:25afaab9540de989f47850',
    messagingSenderId: '667210571249',
    projectId: 'organize-application',
    authDomain: 'organize-application.firebaseapp.com',
    storageBucket: 'organize-application.firebasestorage.app',
    measurementId: 'G-M0V6YBPM85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeR8IBTCkZNGyXBj_o08W_fHKoI9lTn6w',
    appId: '1:667210571249:android:1b30ae8bdf9caad3f47850',
    messagingSenderId: '667210571249',
    projectId: 'organize-application',
    storageBucket: 'organize-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrpbc6k46i8fDqeu9E5vVqlBf4mk2GtNM',
    appId: '1:667210571249:ios:79380f7e1024a999f47850',
    messagingSenderId: '667210571249',
    projectId: 'organize-application',
    storageBucket: 'organize-application.firebasestorage.app',
    iosBundleId: 'com.example.organize',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrpbc6k46i8fDqeu9E5vVqlBf4mk2GtNM',
    appId: '1:667210571249:ios:79380f7e1024a999f47850',
    messagingSenderId: '667210571249',
    projectId: 'organize-application',
    storageBucket: 'organize-application.firebasestorage.app',
    iosBundleId: 'com.example.organize',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCqWRqztOVQeRozkzJOYxDXwbBzWPBzSU',
    appId: '1:667210571249:web:52d327381ad3eb5af47850',
    messagingSenderId: '667210571249',
    projectId: 'organize-application',
    authDomain: 'organize-application.firebaseapp.com',
    storageBucket: 'organize-application.firebasestorage.app',
    measurementId: 'G-98JRVZK0BZ',
  );
}
